services:
  imgproxy:
    image: darthsim/imgproxy
    ports:
      - "8888:8080"
    environment:
      - IMGPROXY_ENABLE_WEBP_DETECTION=true
      - IMGPROXY_ENABLE_AVIF_DETECTION=true
      - IMGPROXY_PREFERRED_FORMATS=webp,avif,jpeg,png,gif
      - IMGPROXY_JPEG_PROGRESSIVE=true
      - IMGPROXY_USE_ETAG=true
